# Generated by Django 5.2.7 on 2025-12-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0010_alter_item_in_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='champion',
            name='partype',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='champion',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
