# Generated by Django 5.2.7 on 2025-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0011_alter_champion_name_alter_champion_partype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rune',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rune',
            name='rune_value',
            field=models.PositiveIntegerField(),
        ),
    ]
