# Generated by Django 5.2.7 on 2025-12-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0012_alter_item_id_alter_rune_id_alter_rune_rune_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
