# Generated by Django 5.2.7 on 2025-12-17 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0013_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Middle'), ('BOTTOM', 'Bottom'), ('UTILITY', 'Support')], max_length=10)),
                ('queue_type', models.IntegerField(choices=[(400, 'Normal Draft'), (420, 'Ranked Solo/Duo'), (430, 'Normal Blind'), (440, 'Ranked Flex'), (450, 'ARAM'), (700, 'Clash'), (720, 'ARAM Clash'), (830, 'Intro Bots'), (840, 'Beginner Bots'), (850, 'Intermediate Bots'), (900, 'URF'), (1020, 'One for All'), (1300, 'Nexus Blitz'), (1400, 'Ultimate Spellbook'), (1700, 'Arena'), (1900, 'Pick URF')], default=420)),
                ('item_build', models.JSONField()),
                ('build_type', models.CharField(choices=[('CORE', 'Core Build'), ('FULL', 'Full Build'), ('SITUATIONAL', 'Situational')], default='CORE', max_length=20)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('winrate', models.FloatField(default=0.0)),
                ('avg_damage', models.BigIntegerField(default=0)),
                ('avg_gold', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-patch', '-winrate'],
            },
        ),
        migrations.CreateModel(
            name='ChampionRoleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Middle'), ('BOTTOM', 'Bottom'), ('UTILITY', 'Support')], max_length=10)),
                ('queue_type', models.IntegerField(choices=[(400, 'Normal Draft'), (420, 'Ranked Solo/Duo'), (430, 'Normal Blind'), (440, 'Ranked Flex'), (450, 'ARAM'), (700, 'Clash'), (720, 'ARAM Clash'), (830, 'Intro Bots'), (840, 'Beginner Bots'), (850, 'Intermediate Bots'), (900, 'URF'), (1020, 'One for All'), (1300, 'Nexus Blitz'), (1400, 'Ultimate Spellbook'), (1700, 'Arena'), (1900, 'Pick URF')], default=420)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('winrate', models.FloatField(default=0.0)),
                ('pickrate', models.FloatField(default=0.0)),
                ('banrate', models.FloatField(default=0.0)),
                ('avg_kills', models.FloatField(default=0.0)),
                ('avg_deaths', models.FloatField(default=0.0)),
                ('avg_assists', models.FloatField(default=0.0)),
                ('avg_kda', models.FloatField(default=0.0)),
                ('avg_cs', models.FloatField(default=0.0)),
                ('avg_damage_dealt', models.BigIntegerField(default=0)),
                ('avg_gold', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-patch', '-winrate'],
            },
        ),
        migrations.CreateModel(
            name='MatchupStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Middle'), ('BOTTOM', 'Bottom'), ('UTILITY', 'Support')], max_length=10)),
                ('queue_type', models.IntegerField(choices=[(400, 'Normal Draft'), (420, 'Ranked Solo/Duo'), (430, 'Normal Blind'), (440, 'Ranked Flex'), (450, 'ARAM'), (700, 'Clash'), (720, 'ARAM Clash'), (830, 'Intro Bots'), (840, 'Beginner Bots'), (850, 'Intermediate Bots'), (900, 'URF'), (1020, 'One for All'), (1300, 'Nexus Blitz'), (1400, 'Ultimate Spellbook'), (1700, 'Arena'), (1900, 'Pick URF')], default=420)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('winrate', models.FloatField(default=0.0)),
                ('winrate_delta', models.FloatField(default=0.0)),
                ('avg_kills_delta', models.FloatField(default=0.0)),
                ('avg_deaths_delta', models.FloatField(default=0.0)),
                ('avg_cs_delta', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-patch', '-winrate'],
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('version', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='match_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='queue_type',
            field=models.IntegerField(blank=True, choices=[(400, 'Normal Draft'), (420, 'Ranked Solo/Duo'), (430, 'Normal Blind'), (440, 'Ranked Flex'), (450, 'ARAM'), (700, 'Clash'), (720, 'ARAM Clash'), (830, 'Intro Bots'), (840, 'Beginner Bots'), (850, 'Intermediate Bots'), (900, 'URF'), (1020, 'One for All'), (1300, 'Nexus Blitz'), (1400, 'Ultimate Spellbook'), (1700, 'Arena'), (1900, 'Pick URF')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='lane',
            field=models.CharField(blank=True, choices=[('TOP', 'Top Lane'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Mid Lane'), ('BOTTOM', 'Bot Lane'), ('NONE', 'None')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='role',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Middle'), ('BOTTOM', 'Bottom'), ('UTILITY', 'Support')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='rune_ids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='matchsummoners',
            name='summoner_spell_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='champion',
            index=models.Index(fields=['name'], name='lol_navo_ch_name_c82903_idx'),
        ),
        migrations.AddIndex(
            model_name='champion',
            index=models.Index(fields=['id'], name='lol_navo_ch_id_b17192_idx'),
        ),
        migrations.AddIndex(
            model_name='matchsummoners',
            index=models.Index(fields=['champion', 'role'], name='lol_navo_ma_champ_role_idx'),
        ),
        migrations.AddIndex(
            model_name='matchsummoners',
            index=models.Index(fields=['summoner', 'champion', 'role'], name='lol_navo_ma_s_c_r_idx'),
        ),
        migrations.AddIndex(
            model_name='summoner',
            index=models.Index(fields=['puuid'], name='lol_navo_su_puuid_d9d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='summoner',
            index=models.Index(fields=['username'], name='lol_navo_su_usernam_a49594_idx'),
        ),
        migrations.AddIndex(
            model_name='summoner',
            index=models.Index(fields=['server'], name='lol_navo_su_server_5fb765_idx'),
        ),
        migrations.AddIndex(
            model_name='summoner',
            index=models.Index(fields=['server', 'username'], name='lol_navo_su_server_d3edf3_idx'),
        ),
        migrations.AddField(
            model_name='buildstats',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_stats', to='lol_navo.champion'),
        ),
        migrations.AddField(
            model_name='championrolestats',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_stats', to='lol_navo.champion'),
        ),
        migrations.AddField(
            model_name='matchupstats',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_stats_as_player', to='lol_navo.champion'),
        ),
        migrations.AddField(
            model_name='matchupstats',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_stats_as_opponent', to='lol_navo.champion'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['is_active'], name='lol_navo_pa_is_acti_546101_idx'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['-version'], name='lol_navo_pa_version_c41a23_idx'),
        ),
        migrations.AddField(
            model_name='matchupstats',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_stats', to='lol_navo.patch'),
        ),
        migrations.AddField(
            model_name='championrolestats',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_role_stats', to='lol_navo.patch'),
        ),
        migrations.AddField(
            model_name='buildstats',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_stats', to='lol_navo.patch'),
        ),
        migrations.AddField(
            model_name='championstat',
            name='patch_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_stats', to='lol_navo.patch'),
        ),
        migrations.AddField(
            model_name='match',
            name='patch_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='lol_navo.patch'),
        ),
        migrations.AddIndex(
            model_name='championstat',
            index=models.Index(fields=['summoner', 'patch_version'], name='lol_navo_ch_summ_patch_idx'),
        ),
        migrations.AddIndex(
            model_name='championstat',
            index=models.Index(fields=['champion', 'patch_version'], name='lol_navo_ch_champ_patch_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-match_timestamp'], name='lol_navo_ma_match_t_38025e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['queue_type', '-match_timestamp'], name='lol_navo_ma_queue_t_daa463_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['patch_version', 'queue_type'], name='lol_navo_ma_patch_v_c0cff3_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['region', '-match_timestamp'], name='lol_navo_ma_region_5d34a8_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupstats',
            index=models.Index(fields=['champion', 'role', 'patch', '-winrate'], name='lol_navo_ma_champio_05b5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupstats',
            index=models.Index(fields=['champion', 'role', 'patch', 'winrate'], name='lol_navo_ma_champio_706d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupstats',
            index=models.Index(fields=['opponent', 'role', 'patch', '-winrate'], name='lol_navo_ma_opponen_cfeafd_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupstats',
            index=models.Index(fields=['patch', 'queue_type', '-games_played'], name='lol_navo_ma_patch_i_163d59_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchupstats',
            constraint=models.UniqueConstraint(fields=('champion', 'opponent', 'role', 'patch', 'queue_type'), name='uniq_matchup'),
        ),
        migrations.AddIndex(
            model_name='championrolestats',
            index=models.Index(fields=['patch', 'queue_type', 'role', '-winrate'], name='lol_navo_ch_patch_i_22278d_idx'),
        ),
        migrations.AddIndex(
            model_name='championrolestats',
            index=models.Index(fields=['champion', 'role', '-patch'], name='lol_navo_ch_champio_a90683_idx'),
        ),
        migrations.AddIndex(
            model_name='championrolestats',
            index=models.Index(fields=['patch', 'queue_type', '-games_played'], name='lol_navo_ch_patch_i_7a2826_idx'),
        ),
        migrations.AddIndex(
            model_name='championrolestats',
            index=models.Index(fields=['patch', 'queue_type', '-pickrate'], name='lol_navo_ch_patch_i_9ef590_idx'),
        ),
        migrations.AddIndex(
            model_name='championrolestats',
            index=models.Index(fields=['patch', 'queue_type', '-banrate'], name='lol_navo_ch_patch_i_2d4ec5_idx'),
        ),
        migrations.AddConstraint(
            model_name='championrolestats',
            constraint=models.UniqueConstraint(fields=('champion', 'role', 'patch', 'queue_type'), name='uniq_champion_role_patch_queue'),
        ),
        migrations.AddIndex(
            model_name='buildstats',
            index=models.Index(fields=['champion', 'role', 'patch', '-games_played'], name='lol_navo_bu_champio_7b3d79_idx'),
        ),
        migrations.AddIndex(
            model_name='buildstats',
            index=models.Index(fields=['champion', 'role', 'patch', '-winrate'], name='lol_navo_bu_champio_ccb25a_idx'),
        ),
        migrations.AddIndex(
            model_name='buildstats',
            index=models.Index(fields=['patch', 'queue_type', 'build_type'], name='lol_navo_bu_patch_i_1ec8b6_idx'),
        ),
    ]
