# Generated by Django 5.2.7 on 2025-12-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0014_buildstats_championrolestats_matchupstats_patch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='puuid',
            field=models.CharField(primary_key=True, max_length=100, serialize=False),
        ),
    ]
