# Generated by Django 5.2.7 on 2025-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0015_increase_puuid_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDragonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Dragon Version',
                'verbose_name_plural': 'Data Dragon Versions',
                'ordering': ['-synced_at'],
            },
        ),
    ]
