# Generated by Django 5.2.7 on 2025-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_navo', '0015_increase_puuid_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='tag',
            field=models.CharField(default='', max_length=5),
        ),
    ]
